// Generated by https://quicktype.io

export class PokemonPage {
    count:    number;
    next:     string;
    previous: null;
    results:  Pokemon[];
}

export class Pokemon {
    name: string;
    url:  string;
    img:  string;
}
